### ISSUE TITLE
HDAWG example_awg_commandtable.py no longer works with new firmware

### ISSUE THREAD

**Issue by Patrick-Poitras** [zhinst/labone-api-examples#1]
I have upgraded the DataServer version as well as the firmware running on the device to version 22.08. Since then we have been getting “hzl_dsp_awg_cmdtbl_parse_json ‘Version string parsing failed!’ errors.” from the DataServer. These also trigger an “Illegal command table version specified in JSON loaded to AWG 1” error on the Webserver Error Log (front-end). 

It seems that the command table schema has changed, and the old examples no longer seem to work with the new data server and firmware. Running on Linux/Ubuntu.

Am able to assist in troubleshooting if necessary.

**Comment by Patrick-Poitras** [comment]
Upgrading the version number in the json to "1.0" did the trick.

**Comment by ghost** [comment]
@Patrick-Poitras thanks for raising this issue.
We have updated the example in Commit [7d5584f](https://github.com/zhinst/labone-api-examples/commit/7d5584f6bbc6ee8bd98c39dea1c1b967ea6e162f). 

I must admit there was no warning that the major version of the command table changed. We will add it to our release notes of LabOne and also make sure that in the future we communicate better if and why the major version changes.
