### ISSUE TITLE
USB connection error. zhinst.core._core.errors.CoreError: ZIAPIServerException with status code: 32792

### ISSUE THREAD

**Issue by nyuvlab** [zhinst/labone-api-examples#3]
We connect PC to SHFQC via USB cable and GUI works fine.

When we run example_rabi.py with interface = "USB", python .\labone-api-examples-release-24.10\shfsg\python\example_rabi.py DEV12513 --interface USB
there's an error:
`
Exception: ZIAPIServerException with status code: 32799 - Invalid argument received. Extended information: Node '/dev12513/sgchannels/0/awg/outputs/0/gains/0' of type 'struct zhinst::CoreDouble' cannot accept a value of type 'class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >'. The two types are incompatible.
Source: io\protocol\session\capnp\client\src\api_deserialization.cpp:77
Exception: ZIAPIServerException with status code: 32799 - Invalid argument received. Extended information: Node '/dev12513/sgchannels/0/awg/outputs/0/gains/1' of type 'struct zhinst::CoreDouble' cannot accept a value of type 'class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >'. The two types are incompatible.
Source: io\protocol\session\capnp\client\src\api_deserialization.cpp:77
Exception: ZIAPIServerException with status code: 32799 - Invalid argument received. Extended information: Node '/dev12513/sgchannels/0/awg/outputs/1/gains/0' of type 'struct zhinst::CoreDouble' cannot accept a value of type 'class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >'. The two types are incompatible.
Source: io\protocol\session\capnp\client\src\api_deserialization.cpp:77
Exception: ZIAPIServerException with status code: 32799 - Invalid argument received. Extended information: Node '/dev12513/sgchannels/0/awg/outputs/1/gains/1' of type 'struct zhinst::CoreDouble' cannot accept a value of type 'class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >'. The two types are incompatible.
Source: io\protocol\session\capnp\client\src\api_deserialization.cpp:77`

It seems the program does not accept interface=USB command line.

However, if we use --interface PCIe or --interface 1GbE, there's only an error "zhinst.core._core.errors.CoreError: ZIAPIServerException with status code: 32792 - Device already connected over a different interface. Extended information: Cannot connect to device DEV12513 using interface 'PCIe'. The device is already connected using interface 'USB'." which is as expected, so it at least proves "PCIe" and "1GbE" are valid command line input.

Could you help us look into this?

**Comment by ghost** [comment]
Thanks for bringing this up. It is indeed a bug in our examples' command line interface/parsing. 

The good thing is that it is not related to your connection or instrument 😇 but to the API examples themself.

We will soon release a fix for the API examples. In the meantime, the following solution bypasses the problem.

In the very first line of the example (e.g. https://github.com/zhinst/labone-api-examples/blob/release-24.10/shfsg/python/example_rabi.py#L67) add `gains = (0.0, 1.0, 1.0, 0.0)`. This ensures the gains are processed as a list of double and not as a list of chars

**Comment by ghost** [comment]
https://github.com/zhinst/labone-api-examples/commit/7ef194d8135f0ad14b1bbd2d5a2e46d51af24f42 fixed the issue. 

The command line arguments (including the default values) are now parsed correctly.

Feel free to reach out if you still encounter any issues.
